### ISSUE TITLE
Install fails on Raspbian due to torbrowser-launcher not being installable

### ISSUE THREAD

**Issue by LosEagle** [micahflee/onionshare#1007]
There is onionshare version in Raspbian repos which cannot be installed due to
```
The following packages have unmet dependencies:
 onionshare : Depends: torbrowser-launcher but it is not installable
E: Unable to correct problems, you have held broken packages.
```
As far as I understand, onionshare does not actually need torbrowser to function. System tor should be enough so why does it depend on this package? Is there any workaround for this whatsover?

**Comment by mig5** [comment]
According to https://github.com/micahflee/onionshare/blob/develop/stdeb.cfg OnionShare doesn't depend on torbrowser-launcher directly.

It is apparently already fixed by the downstream Debian maintainer,  see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=916889 

My guess is Raspbian is not based on new enough version of Debian to benefit from the change in Debian.

>  Is there any workaround for this whatsover?

I recommend cloning the git repo, checking out the master branch, and running `install/build_deb.sh`, from which you'll get your own .deb package which you can then install with `dpkg -i`.

**Comment by LosEagle** [comment]
Raspbian seems to lack certain python dependencies which prevents me from building it there directly. I've tried building it in virtual Lubuntu environment with success but it still can't be installed without those dependencies. I guess I'm going to have to wait for newer version of Raspbian or Flatpak release then :(

**Comment by micahflee** [comment]
No longer an issue
