### ISSUE TITLE
Web page static assets are missing in packages built off of develop branch

### ISSUE THREAD

**Issue by Baccount** [micahflee/onionshare#693]
When compiling with Qt-5.10.0, hosting the server causes a blank page when I visit the .onion.

1. update QT to Qt-5.10.0, Python 3.6.5 and PyInstaller: 3.3.1
2. open onionshare and start a share, then navigate to the .onion using Tor Browser 7.5.4 and the page should look like this.
I tested this using the latest  **develop** code.
<img width="1000" alt="bug" src="https://user-images.githubusercontent.com/10781882/40010569-01bf2862-575a-11e8-9ed4-c08b7f497a9d.png">

Here is the --debug output
```
[May 14 2018 09:36:10] OnionShareGui.copy_url
127.0.0.1 - - [14/May/2018 09:36:21] "GET /superior-upchuck HTTP/1.1" 200 -
127.0.0.1 - - [14/May/2018 09:36:21] "GET /static/css/style.css HTTP/1.1" 404 -
127.0.0.1 - - [14/May/2018 09:36:22] "GET /static/img/favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [14/May/2018 09:36:22] "GET /static/img/web_file.png HTTP/1.1" 404 -
127.0.0.1 - - [14/May/2018 09:36:23] "GET /static/img/logo.png HTTP/1.1" 404 -
```

**Comment by mig5** [comment]
There's a good chance this is fixed by #688, as it looks to be just because the /static assets are missing.

**Comment by Baccount** [comment]
@mig5 this bug is still occurring after I recompiled with your commit included.

**Comment by mig5** [comment]
@Baccount yes I reproduce, sorry. There's another place it needs fixing. Will push a PR shortly.

**Comment by Baccount** [comment]
Fixed on my end with your comment 41c10b1ea29ca94b6f66c4cbc7614c3f541d7dd5, thanks @mig5
